AplicacaoWebCantina/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using AplicacaoWebCantina.Models.Clientes;
using AplicacaoCantina.Utils.Entidades;
using MySqlX.XDevAPI.Common;
using MySqlX.XDevAPI;

namespace AplicacaoWebCantina.Controllers
{
    public class ClientesController : Controller
    {

        public IActionResult record(ClienteModel model)
        {

            return View(model);
        }

        [HttpPost]
        public IActionResult save(ClienteModel model)
        {
            Cliente cliente = model.GetEntidade();

            if (model.Id > 0)
            {
                cliente.Update();
            }
            else
            {
                cliente.Create();
            }
            return RedirectToAction("index");
        }


        public IActionResult excluir(ClienteModel model)
        {
            Cliente cliente = model.GetEntidade();
            cliente.Delete();

            return RedirectToAction("index");
        }

        public IActionResult Index()
        {
            var model = new ClientesModel();
            model.Clientes = new List<ClienteModel>();

            var clientes = new Cliente().GetAll();

            model.Clientes = clientes.Select(clienteEntidade => new ClienteModel(clienteEntidade)).ToList();

            return View(model);
        }

        [HttpGet("api/v1/Clientes")]
        public IActionResult Get()
        {
            var result = new Cliente().GetAll().Select(cliente => new ClienteModel(cliente));
           
            return Ok(result);
        }

        [HttpPost("api/v1/Cliente")]
        public IActionResult Post([FromBody]ClienteModel cliente)
        {
            var clienteEntidade = cliente.GetEntidade();
            clienteEntidade.Create();

            return Ok("Cliente Adicionado");
        }

        [HttpPut("api/v1/Cliente/{id}")]    
        public IActionResult Put(int id, [FromBody] ClienteModel clienteAtualizado)
        {
            var clienteDB = new Cliente().Get(id);
            clienteDB.Nome = clienteAtualizado.Nome ?? clienteDB.Nome;
            clienteDB.Update();

            return Ok("Cliente atualizado!");
        }

        [HttpDelete("api/v1/Clientes/{id}")]
        public IActionResult Delete(int id)
        {
            var cliente = new Cliente().Get(id);
            cliente.Delete();

            return Ok("Cliente Deletado");
        }
    }
}

AplicacaoWebCantina/Controllers/EstoqueController.cs
using AplicacaoWebCantina.Models.Estoque;
using AplicacaoWebCantina.Models.Produtos;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AplicacaoWebCantina.Controllers
{
    public class EstoqueController : Controller
    {
        // Dados mocados
        private static List<EstoqueModel> Estoques = new List<EstoqueModel>
{
             new EstoqueModel { ID = 1, ProdutoId = 101, QuantidadeAtual = 50, QuantidadeMinima = 10, DataUltimaReposicao = DateTime.Now.AddMonths(-1) },
             new EstoqueModel { ID = 2, ProdutoId = 102, QuantidadeAtual = 5, QuantidadeMinima = 10, DataUltimaReposicao = DateTime.Now.AddMonths(-2) }
};

        // Mostrar a View do estoque
        public IActionResult Index()
        {
            foreach (var estoque in Estoques)
            {
                estoque.Produto = new ProdutoModel { ID = estoque.ProdutoId, Nome = "Produto " + estoque.ProdutoId };
            }

            return View(Estoques);
        }

        public IActionResult Edit(int id)
        {
            var estoque = Estoques.FirstOrDefault(e => e.ID == id);
            if (estoque == null)
                return NotFound();

            var produto = new ProdutoModel { ID = estoque.ProdutoId, Nome = "Produto " + estoque.ProdutoId };

            estoque.Produto = produto;

            return View(estoque);
        }


        [HttpPost]
        public IActionResult Edit(EstoqueModel estoque)
        {
            var estoqueExistente = Estoques.FirstOrDefault(e => e.ID == estoque.ID);
            if (estoqueExistente != null)
            {
                estoqueExistente.QuantidadeAtual = estoque.QuantidadeAtual;
                estoqueExistente.DataUltimaReposicao = estoque.DataUltimaReposicao;
                estoqueExistente.QuantidadeMinima = estoque.QuantidadeMinima;
            }
            return RedirectToAction("Index");
        }
    }
}

AplicacaoWebCantina/Controllers/PedidoController.cs
using AplicacaoCantina.Models;
using AplicacaoCantina.Utils.Entidades;
using Microsoft.AspNetCore.Mvc;
using System;

namespace AplicacaoCantina.Controllers
{
    public class PedidoController : Controller
    {
        private readonly PedidoModel _pedidoModel;

        public PedidoController()
        {
            _pedidoModel = new PedidoModel();
        }

        // GET: Pedido
        public IActionResult Index()
        {
            var pedidos = _pedidoModel.GetAllPedidos();
            return View(pedidos);
        }

        // GET: Pedido/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pedido/Create
        [HttpPost]
        public IActionResult Create(Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _pedidoModel.CreatePedido(pedido);
                return RedirectToAction("Index");
            }
            return View(pedido);
        }

        // GET: Pedido/Edit/5
        public IActionResult Edit(int id)
        {
            var pedido = _pedidoModel.GetPedidoById(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        [HttpPost]
        public IActionResult Edit(int id, Pedido pedido)
        {
            if (id != pedido.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _pedidoModel.UpdatePedido(pedido);
                return RedirectToAction("Index");
            }
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public IActionResult Delete(int id)
        {
            var pedido = _pedidoModel.GetPedidoById(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _pedidoModel.DeletePedido(id);
            return RedirectToAction("Index");
        }
    }
}

AplicacaoWebCantina/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using AplicacaoWebCantina.Models.Produtos;
using AplicacaoCantina.Utils.Entidades;
using AplicacaoWebCantina.Models.Clientes;

namespace AplicacaoWebCantina.Controllers
{
    public class ProdutosController : Controller
    {

        public IActionResult record(ProdutoModel model)
        {

            return View(model);
        }

        [HttpPost]
        public IActionResult save(ProdutoModel model)
        {
            Produto produto = model.GetEntidade();

            if (model.ID > 0)
            {
                produto.Update();
            }
            else
            {
                produto.Create();
            }
            return RedirectToAction("index");
        }


        public IActionResult excluir(ProdutoModel model)
        {
            Produto produto = model.GetEntidade();
            produto.Delete();

            return RedirectToAction("index");
        }

        public IActionResult Index()
        {
            var model = new ProdutosModel();
            model.Produtos = new List<ProdutoModel>();

            var produtos = new Produto().GetAll();

            model.Produtos = produtos.Select(produtoEntidade => new ProdutoModel(produtoEntidade)).ToList();

            return View(model);
        }

        [HttpGet("api/v1/Produtos")]
        public IActionResult Get()
        {
            var result = new Produto().GetAll().Select(produto => new ProdutoModel(produto));

            return Ok(result);
        }

        [HttpPost("api/v1/Produto")]
        public IActionResult Post([FromBody] ProdutoModel produto)
        {
            var produtoEntidade = produto.GetEntidade();
            produtoEntidade.Create();

            return Ok("Produto Adicionado");
        }

        [HttpPut("api/v1/Produto/{id}")]
        public IActionResult Put(int id, [FromBody] ProdutoModel produtoAtualizado)
        {
            var produtoDB = new Produto().Get(id);
            produtoDB.Nome = produtoAtualizado.Nome ?? produtoDB.Nome;
            produtoDB.Update();

            return Ok("Produto atualizado!");
        }

        [HttpDelete("api/v1/Produtos/{id}")]
        public IActionResult Delete(int id)
        {
            var produto = new Produto().Get(id);
            produto.Delete();

            return Ok("Produto Deletado");
        }
    }
}

AplicacaoWebCantina/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Variável de Sabor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacaoWebCantina.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white position-fixed" asp-area="" asp-controller="Home" asp-action="Index">Variável de Sabor</a>
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Clientes" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Pedido" asp-action="Index">Pedido</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Produtos" asp-action="Index">Produto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Estoque" asp-action="Index">Estoque</a>
                        </li>   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <h3>Váriavel de Sabor</h3>
            <p>Conexão com o banco @(AplicacaoCantina.Utils.Database.DBConnection.TestarConexao())</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>